### ISSUE TITLE
Prometheus-with-Helm docs were deleted

### ISSUE THREAD

**Issue by LukeShu** [datawire/ambassador-docs#169]
In [425570157c14b1fb7da4a970aa06d39c0b781117](https://github.com/datawire/ambassador-docs/commit/425570157c14b1fb7da4a970aa06d39c0b781117#diff-b7c6d657c777dafdac63f9ca8d69f94b) we removed references to using Helm to install Ambassador.  However, it also over-zealously removed docs on using Prometheus-as-installed-by-Helm from `user-guide/monitoring.md`.  Those docs continue to be useful.

**Comment by scoyle391** [comment]
@khussey just the monitoring page? I also found a reference to Prometheus with Helm in reference/statistics.

**Comment by khussey** [comment]
> @khussey just the monitoring page? I also found a reference to Prometheus with Helm in reference/statistics.

@LukeShu ^

**Comment by LukeShu** [comment]
> > @khussey just the monitoring page? I also found a reference to Prometheus with Helm in reference/statistics.
> 
> @LukeShu ^

I think [that section](https://github.com/datawire/ambassador-docs/commit/425570157c14b1fb7da4a970aa06d39c0b781117#diff-c91f8a43b8c2c819729d20b0b456bbbcL65-L79) should also be restored. @nbkrause?
