### ISSUE TITLE
AuthService page isn't about AES

### ISSUE THREAD

**Issue by LukeShu** [datawire/ambassador-docs#238]
The AuthService page (`reference/auth-service.md`) should be edited to clarify that OSS users should use an AuthService, but that AES users are discouraged from using an AuthService, and should use Filters instead.

- The big downside of an AuthService is *there can only be one* for all of Ambassador.  An "External" Filter (non-OSS) is a drop-in replacement for an AuthService, and there can be many of them, orchestrated by a FilterPolicy.
- AES itself wants to be the AuthService.  Using your own AuthService means deleting the `ambassador-edge-stack-auth` AuthService that is part of aes.yaml, which will disable a substantial portion of the non-OSS functionality, including the ACME client.
- Perhaps some of the information in the AuthService page should be copied/moved to the docs about External Filters.

**Comment by scoyle391** [comment]
https://datawire-oss.slack.com/archives/CAULN7S76/p1579467736107400

**Comment by scoyle391** [comment]
https://datawire-oss.slack.com/archives/CAULN7S76/p1579366421071100
https://datawire-oss.slack.com/archives/CAULN7S76/p1579372951079400
