### ISSUE TITLE
Request: Callout how to access the AES admin page with upgrades

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador-docs#248]
The AES install instructions tell users to go to `https://{{AES_URL}}/` to access the admin page. However, this does not work if you have a `Mapping` with `prefix: /`.

Therefore, I propose we edit the upgrade doc to just tell users to go to `https://{{AES_URL}}/edge_stack/admin` so there is no confusion

**Comment by ark3** [comment]
The docs could just have people download and install Edge Control and then tell them to use `edgectl login -n <namespace> <AES_host>`. Those instructions exist in the login gate (and should stay there!), but I think it's a better experience to avoid that extra step entirely, especially for the upgrade (migration) scenario.

**Comment by scoyle391** [comment]
https://datawire-oss.slack.com/archives/CAULN7S76/p1579366421071100
https://datawire-oss.slack.com/archives/CAULN7S76/p1579372951079400
